name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc:
    path: ../

flutter:
  uses-material-design: true