name: bloc
description: The goal of this package is to make it easy to implement the BLoC Design Pattern (Business Logic Component).
version: 0.3.0
author: felix.angelov <felangelov@gmail.com>
homepage: https://github.com/felangel/bloc

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  rxdart: ">=0.19.0 <1.0.0"
  flutter:
    sdk: flutter
  meta: ^1.1.0
  rx_command: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ">=1.3.0 <2.0.0"
